apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-configs
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            cluster.saas.aws/type: data-plane
  template:
    metadata:
      name: '{{name}}-platform'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://git-codecommit.{{metadata.labels.aws-region}}.amazonaws.com/v1/repos/saas-platform-configs'
        targetRevision: main
        path: .
        directory:
          recurse: true
          exclude: '{applicationsets/*,examples/*}'
      destination:
        server: '{{server}}'
        namespace: tenants
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RenderHelm=true
