import {
  BedrockRuntimeClient,
  ConverseCommand
} from '@aws-sdk/client-bedrock-runtime';
import { TenantTier } from '../types/tenant';

/**
 * AI Game Host - Bedrock clue generation
 *
 * The AI Game Host replaces the plain "too high" / "too low" feedback with a
 * natural-language clue about the target number. The clue is generated by an
 * Amazon Bedrock model whose identity depends on the tenant tier:
 *   - basic tier: Claude Haiku (fast, low cost)
 *   - pro tier:   Claude Sonnet (richer, more creative clues)
 *
 * IMPORTANT: This service never decides the game outcome. The deterministic
 * game engine computes win/lose/score/guesses-remaining. This service only
 * phrases a clue from facts the server already knows to be true, so a clue can
 * never be factually wrong. If Bedrock is disabled, errors, or times out,
 * generateClue() returns null and the caller falls back to the plain feedback.
 */

// Feature flag and model configuration from environment variables
const AI_HOST_ENABLED = (process.env.AI_HOST_ENABLED || 'false').toLowerCase() === 'true';
const BEDROCK_MODEL_ID = process.env.BEDROCK_MODEL_ID || '';
const AWS_REGION = process.env.AWS_REGION || 'us-east-1';

// Keep the Bedrock call off the game's critical path. If the model does not
// respond quickly we abandon the clue and let the caller fall back. Sonnet-class
// models can take a few seconds on a cold call, so the default allows for that.
const CLUE_TIMEOUT_MS = parseInt(process.env.AI_HOST_TIMEOUT_MS || '5000', 10);

// Lazily initialized client so importing this module has no side effects when
// the feature is disabled (e.g. in unit tests).
let bedrockClient: BedrockRuntimeClient | null = null;

function getClient(): BedrockRuntimeClient {
  if (!bedrockClient) {
    bedrockClient = new BedrockRuntimeClient({
      region: AWS_REGION,
      maxAttempts: 1 // fail fast; the game must not wait on retries
    });
  }
  return bedrockClient;
}

/**
 * True facts about the target number relative to the player's guess.
 * Every field is derived deterministically by the server, so the model can
 * only ever restate something that is true.
 */
export interface TargetFacts {
  direction: 'higher' | 'lower'; // target is higher/lower than the guess
  distance: 'very close' | 'close' | 'far'; // how far the guess is from the target
  parity: 'even' | 'odd';
  isPrime: boolean;
  digitSum: number;
  rangeBand: string; // e.g. "between 1 and 25"
}

/**
 * Determine whether a positive integer is prime.
 */
function isPrimeNumber(n: number): boolean {
  if (n < 2) {
    return false;
  }
  for (let i = 2; i * i <= n; i++) {
    if (n % i === 0) {
      return false;
    }
  }
  return true;
}

/**
 * Sum the decimal digits of a number (e.g. 47 -> 11).
 */
function sumDigits(n: number): number {
  return Math.abs(n)
    .toString()
    .split('')
    .reduce((total, digit) => total + parseInt(digit, 10), 0);
}

/**
 * Build the set of true facts about the target relative to the guess.
 * Pure function with no I/O so it is fully unit testable.
 *
 * @param guess - The player's most recent guess (1-100)
 * @param target - The secret target number (1-100)
 */
export function buildTargetFacts(guess: number, target: number): TargetFacts {
  const diff = Math.abs(target - guess);

  let distance: TargetFacts['distance'];
  if (diff <= 5) {
    distance = 'very close';
  } else if (diff <= 15) {
    distance = 'close';
  } else {
    distance = 'far';
  }

  // Range bands in blocks of 25 across the 1-100 board
  let rangeBand: string;
  if (target <= 25) {
    rangeBand = 'between 1 and 25';
  } else if (target <= 50) {
    rangeBand = 'between 26 and 50';
  } else if (target <= 75) {
    rangeBand = 'between 51 and 75';
  } else {
    rangeBand = 'between 76 and 100';
  }

  return {
    direction: target > guess ? 'higher' : 'lower',
    distance,
    parity: target % 2 === 0 ? 'even' : 'odd',
    isPrime: isPrimeNumber(target),
    digitSum: sumDigits(target),
    rangeBand
  };
}

/**
 * Build the prompt sent to the model. The instructions constrain the model to
 * the supplied facts so it cannot invent misleading information.
 */
function buildPrompt(facts: TargetFacts, tier: TenantTier): { system: string; user: string } {
  const factLines = [
    `- The target is ${facts.direction} than the player's last guess.`,
    `- The guess is ${facts.distance} to the target.`,
    `- The target is an ${facts.parity} number.`,
    `- The target is ${facts.isPrime ? 'a prime' : 'not a prime'} number.`,
    `- The digits of the target add up to ${facts.digitSum}.`,
    `- The target is ${facts.rangeBand}.`
  ].join('\n');

  // Both tiers use the same true facts. The tier only changes the style, which
  // is where the stronger model earns its keep.
  const style =
    tier === 'pro'
      ? 'Write a short, playful riddle (one or two sentences) that combines two of the facts. Be creative but never state the number itself.'
      : 'Write one short, friendly sentence that reveals exactly one of the facts. Never state the number itself.';

  const system =
    'You are the AI Game Host for a number guessing game where the target is between 1 and 100. ' +
    'You give the player a clue for their next guess. ' +
    'You may only use the facts provided. Never reveal the exact number. ' +
    'Never contradict a fact. Keep the clue under 30 words and do not add commentary.';

  const user = `Facts you may use:\n${factLines}\n\n${style}`;

  return { system, user };
}

/**
 * Generate a natural-language clue for the player's guess.
 *
 * Returns null when the feature is disabled, misconfigured, or the model call
 * fails or times out. Callers MUST treat null as "no clue" and fall back to the
 * deterministic feedback text.
 *
 * @param guess - The player's most recent guess
 * @param target - The secret target number
 * @param tier - The tenant tier (selects the phrasing style)
 */
export async function generateClue(
  guess: number,
  target: number,
  tier: TenantTier
): Promise<string | null> {
  if (!AI_HOST_ENABLED || !BEDROCK_MODEL_ID) {
    return null;
  }

  const facts = buildTargetFacts(guess, target);
  const { system, user } = buildPrompt(facts, tier);

  try {
    const command = new ConverseCommand({
      modelId: BEDROCK_MODEL_ID,
      system: [{ text: system }],
      messages: [{ role: 'user', content: [{ text: user }] }],
      inferenceConfig: {
        maxTokens: 100,
        temperature: 0.7
      }
    });

    const response = await getClient().send(command, {
      abortSignal: AbortSignal.timeout(CLUE_TIMEOUT_MS)
    });

    const text = response.output?.message?.content?.[0]?.text?.trim();
    return text && text.length > 0 ? text : null;
  } catch (error) {
    // Any failure (throttling, timeout, access denied, malformed response)
    // degrades gracefully to the deterministic feedback.
    console.warn(
      `[AI Game Host] clue generation failed, falling back to plain feedback: ${
        error instanceof Error ? error.message : 'unknown error'
      }`
    );
    return null;
  }
}

/**
 * Whether the AI Game Host feature is enabled and configured.
 */
export function isAiHostEnabled(): boolean {
  return AI_HOST_ENABLED && BEDROCK_MODEL_ID.length > 0;
}
